title = "123k.pl"
baseURL = "https://123k.pl"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
[languages.en]
  title = "123k.pl" 
  weight = 1
  contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "umiarkowanie ciekawe rzeczy"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/IMG_2941.JPG"
  recent_posts_number = 0
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/efwe"
